name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        install_components: kubectl

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    
    - name: Clone vault
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'pauldchang'
        repository: 'vault'
    
    - name: Access cloned repo
      run: |
         cd vault
         ls -la
    - name: Deploy with Helm
      env:
        CLOUDSDK_PYTHON: /usr/bin/python3
      run: |
        gcloud components update
        gcloud container clusters get-credentials gke-project-426921-gke --region us-east5 --project gke-project-426921
        helm repo add hashicorp https://helm.releases.hashicorp.com
        helm install my-vault hashicorp/vault --version 0.28.0
        
